# Generated by Django 5.2.6 on 2025-11-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_address',
            field=models.CharField(default='Chưa đăng kí shop', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_name',
            field=models.CharField(default='Chưa đăng kí shop', max_length=255),
        ),
    ]
